<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="287893" started-at="2017-08-07T08:41:03Z" finished-at="2017-08-07T08:45:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="287893" started-at="2017-08-07T08:41:03Z" finished-at="2017-08-07T08:45:51Z">
      <class name="finalTest.FinalTest">
        <test-method status="FAIL" signature="f()[pri:0, instance:finalTest.FinalTest@6a024a67]" name="f" is-config="true" duration-ms="0" started-at="2017-08-07T14:11:03Z" finished-at="2017-08-07T14:11:03Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at finalTest.BaseClass.logIn(BaseClass.java:86)
	at finalTest.FinalTest.f(FinalTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="g()[pri:0, instance:finalTest.FinalTest@6a024a67]" name="g" duration-ms="0" started-at="2017-08-07T14:15:51Z" finished-at="2017-08-07T14:15:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- g -->
        <test-method status="SKIP" signature="h()[pri:0, instance:finalTest.FinalTest@6a024a67]" name="h" is-config="true" duration-ms="0" started-at="2017-08-07T14:15:51Z" finished-at="2017-08-07T14:15:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- h -->
      </class> <!-- finalTest.FinalTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
